In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant",30)

[27, 4]

In [4]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[9, 10], [27, 4], [22, 12], [5, 2, 25], [21, 1, 23], [20, 10], [8, 1, 17], [27, 27], [27, 25], [21, 11]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[ 9 10  0]
 [27  4  0]
 [22 12  0]
 [ 5  2 25]
 [21  1 23]
 [20 10  0]
 [ 8  1 17]
 [27 27  0]
 [27 25  0]
 [21 11  0]]


In [10]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))


In [11]:
X = padded_reviews
y = sentiment

In [12]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [13]:
model.fit(X, y, epochs=10, verbose=0)

In [15]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9000 - loss: 0.6782


0.8999999761581421

In [16]:
model.get_layer('embedding').get_weights()

[array([[-9.1885580e-03,  2.6506523e-02, -4.2211518e-02,  4.5596141e-02,
          5.3464402e-02],
        [ 2.2254059e-02, -2.0354291e-02, -1.1287581e-02,  1.6012184e-02,
          4.5932621e-02],
        [ 2.0493902e-02, -2.1494303e-02,  1.6585316e-03, -3.0758567e-02,
         -3.4410596e-02],
        [-3.3840977e-02, -1.1685502e-02, -4.4443607e-03,  2.9454235e-02,
          3.1664614e-02],
        [-3.0669460e-02, -5.1542524e-02,  3.6862327e-03,  5.0392136e-02,
          2.3983015e-02],
        [-4.5670304e-03, -1.6774699e-02,  4.1047700e-02,  2.6310212e-03,
         -6.9058873e-03],
        [-2.1604169e-02,  2.3821142e-02, -3.6277659e-03,  4.0271033e-02,
         -8.0014952e-03],
        [-2.5930023e-02,  1.5165392e-02,  1.2723319e-03, -1.7592490e-02,
          6.9078431e-03],
        [ 1.3645114e-02,  5.5018503e-02, -5.8050090e-03, -3.8327109e-02,
         -1.7723998e-02],
        [-2.7255321e-02,  3.5723589e-02,  5.6555439e-02, -5.2002454e-03,
          1.4904768e-02],
        [-